package com.tweetapp.tweet;

import java.util.Date;

import org.springframework.data.annotation.Id;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.tweetapp.usersdetails.User;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.Setter;

@DynamoDBTable(tableName = "Tweet")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Component
public class Tweet {
	
	//@Id TweetAttr tweetAttr;
	
	@DynamoDBHashKey Long id;
	
	@DynamoDBAttribute String loginId;
	
//	@DynamoDBHashKey(attributeName = "id")
//	public Long getId() {return tweetAttr.getId();}
//	public void setId(Long id) { tweetAttr.setId(id);}
//
//	@DynamoDBRangeKey(attributeName = "loginId")
//	public String getLoginId() {return tweetAttr.getLoginId();}
//	public void setLoginId(String id) { tweetAttr.setLoginId(id);}

	@DynamoDBAttribute String tweets;
	@DynamoDBAttribute Date date;
	


}
