package com.tweetapp.likes;

import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.Setter;

@DynamoDBTable(tableName = "Likes")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Component
public class Likes {

	@DynamoDBHashKey Long id;
	
	@DynamoDBAttribute long likes;
	
}
