amazon:
  aws:
    accesskey: AKIARQO2NI74232HJHO6
    region: ap-south-1
    secretkey: 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
  dynamodb:
    endpoint: dynamodb.ap-south-1.amazonaws.com
server:
  port: 5000
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: TweetApp